import { std } from "wow/wotlk";

std.Items.create("default", "eye-of-kezaan")
    .Name.enGB.set("Blind Eye of Kezaan")
    .ItemLevel.set(264)
    .Quality.PURPLE.set()
    .DisplayInfo.set(19785)
    .Flags.UNIQUE_EQUIPPED.set(1)
    .InventoryType.TRINKET.set()
    .Stats.addHitRating(164)
    .Stats.addStamina(123)
    .Stats.addArmorPenetrationRating(233)
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.HEROIC.set(1)
    .Spells.addGet()
    .Spell.set(80900)
    .ProcsPerMinute.set(5)
    .Trigger.CHANCE_ON_HIT.set()
    .Cooldown.set(0)