import { std } from "wow/wotlk";

std.DBC.ScalingStatDistribution.add(372)
    .Maxlevel.set(80)
    .StatID.setIndex(0, 4)
    .StatID.setIndex(1, 7)
    .StatID.setIndex(2, 32)
    .StatID.setIndex(3, 31)
    .StatID.setIndex(4, 38)

std.DBC.ScalingStatDistribution.add(374)
    .Maxlevel.set(80)
    .StatID.setIndex(0, 3)
    .StatID.setIndex(1, 7)
    .StatID.setIndex(2, 32)
    .StatID.setIndex(3, 31)
    .StatID.setIndex(4, 38)
    .StatID.setIndex(5, 36)

std.DBC.ScalingStatDistribution.add(375)
    .Maxlevel.set(80)
    .StatID.setIndex(0, 5)
    .StatID.setIndex(1, 7)
    .StatID.setIndex(2, 32)
    .StatID.setIndex(3, 31)
    .StatID.setIndex(4, 45)
    .StatID.setIndex(5, 6)
    .StatID.setIndex(6, 36)

std.DBC.ScalingStatDistribution.add(376)
    .Maxlevel.set(80)
    .StatID.setIndex(0, 3)
    .StatID.setIndex(1, 5)
    .StatID.setIndex(2, 7)
    .StatID.setIndex(3, 32)
    .StatID.setIndex(4, 37)
    .StatID.setIndex(5, 38)
