import { std } from "wow/wotlk";

std.Spells.create('mod', 'boost')
    .Name.enGB.set('Character Boost')
    .Icon.setPath('spell_holy_holyguidance')
    .Description.enGB.set('With this Guide, you will unlock your Potential and become level 60 in an instance!')
    .Effects.addGet()
    .Type.DUMMY.set()
    .ImplicitTargetA.UNIT_CASTER.set()

std.Spells.create('mod', 'boost-req')
    .Name.enGB.set(`Low-Level Character`)
    .Attributes.IS_PASSIVE.set(1)
    .Attributes.IS_HIDDEN_FROM_LOG.set(1)
    .Attributes.IS_HIDDEN_IN_SPELLBOOK.set(1)
    .Levels.set(80917, 1, 55)
    .Effects.addGet()
    .Type.APPLY_AURA.set()
    .Type.DUMMY.set()
    .ImplicitTargetA.UNIT_CASTER.set()

std.Items.create('mod', 'CharacterBoost')
    .Name.enGB.set("Medivh's Guide to Quick Power")
    .Description.enGB.set("UNEQUIP ALL ITEMS BEFORE USE!")
    .Class.CONSUMABLE.set()
    .Quality.HEIRLOOM.set()
    .Flags.add(["BIND_TO_ACCOUNT", "HEROIC", "REFUNDABLE"])
    .ItemLevel.set(93)
    .Requirements.Level.set(1)
    .Requirements.Spell.set(80917)
    .MaxStack.set(1)
    .DisplayInfo.setSimpleIcon('mod', 'BoostTome', 'inv_misc_book_07')
    .Spells.addGet()
    .Spell.set(80904)
    .Trigger.ON_USE.set()
    .Charges.Raw.set(-1)