import { std } from "wow/wotlk";
import { effectToPath } from "wow/wotlk/std/Item/ItemVisualEffect";

std.Items.create('default', 'enchanted-head')
    .Name.enGB.set('Enchanted Arcanist Crown')
    .Quality.HEIRLOOM.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(31517)
    .Class.CLOTH_EQUIP.set()
    .InventoryType.set("HEAD")
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .ScalingStats.set(375, 8388616)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.Items.create('default', 'enchanted-shoulders')
    .Name.enGB.set('Enchanted Arcanist Mantle')
    .Quality.HEIRLOOM.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(30586)
    .Class.CLOTH_EQUIP.set()
    .InventoryType.set("SHOULDER")
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .ScalingStats.set(375, 8388616)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.Items.create('default', 'enchanted-chest')
    .Name.enGB.set('Enchanted Arcanist Robes')
    .Quality.HEIRLOOM.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(30581)
    .Class.CLOTH_EQUIP.set()
    .InventoryType.set("CHEST")
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .ScalingStats.set(375, 8388616)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    
std.Items.create('default', 'enchanted-wrists')
    .Name.enGB.set('Enchanted Arcanist Bindings')
    .Quality.HEIRLOOM.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(30584)
    .Class.CLOTH_EQUIP.set()
    .InventoryType.set("WRISTS")
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .ScalingStats.set(375, 8388616)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.Items.create('default', 'enchanted-hands')
    .Name.enGB.set('Enchanted Arcanist Gloves')
    .Quality.HEIRLOOM.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(30585)
    .Class.CLOTH_EQUIP.set()
    .InventoryType.set("HANDS")
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .ScalingStats.set(375, 8388616)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.Items.create('default', 'enchanted-waist')
    .Name.enGB.set('Enchanted Arcanist Belt')
    .Quality.HEIRLOOM.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(30583)
    .Class.CLOTH_EQUIP.set()
    .InventoryType.set("WAIST")
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .ScalingStats.set(375, 8388616)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.Items.create('default', 'enchanted-legs')
    .Name.enGB.set('Enchanted Arcanist Leggings')
    .Quality.HEIRLOOM.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(30582)
    .Class.CLOTH_EQUIP.set()
    .InventoryType.set("LEGS")
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .ScalingStats.set(375, 8388616)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.Items.create('default', 'enchanted-feet')
    .Name.enGB.set('Enchanted Arcanist Boots')
    .Quality.HEIRLOOM.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(30587)
    .Class.CLOTH_EQUIP.set()
    .InventoryType.set("FEET")
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .ScalingStats.set(375, 8388616)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.Items.create('default', 'Enchanted-cloak')
    .Name.enGB.set('Enchanted Blanket')
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(28951)
    .Quality.set("HEIRLOOM")
    .Class.CLOTH_EQUIP.set()
    .InventoryType.set("BACK")
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .ScalingStats.set(375, 8388616)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.ItemSet.create('default', 'Arcanist-Heirloom')
    .Name.enGB.set('Enchanted Heirloom Set')
    .Items.addId(60033)
    .Items.addId(60034)
    .Items.addId(60035)
    .Items.addId(60036)
    .Items.addId(60037)
    .Items.addId(60038)
    .Items.addId(60039)
    .Items.addId(60040)
    .Spells.addMod(x=>x
        .Spell.set(41657)
        .Threshold.set(3)
    )
    .Spells.addMod(x=>x
        .Spell.set(41656)
        .Threshold.set(5)
    )
    .Spells.addMod(x=>x
        .Spell.set(23545)
        .Threshold.set(8)
    )

// console.log(std.Spells.load(23042).codify({}))
std.Spells.load(41657).Effects.mod(0, (effects)=>{
    effects.PointsBase.set(47)
})
std.Spells.load(41656).Effects.mod(0, (effects)=>{
    effects.PointsBase.set(-79)
})
std.Spells.load(23545).Effects.mod(0, (effects)=>{
    effects.PointsBase.set(-46)
})

