import { std } from "wow/wotlk";

// Charged Ten Storms Heirlooms

std.Items.create('default', 'Charged-TenStorms-Helm')
    .Name.enGB.set("Charged Helm of Ten Storms")
    .Armor.set(60)
    .InventoryType.HEAD.set()
    .ClassMask.SHAMAN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(34217)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Charged-TenStorms-Shoulder')
    .Name.enGB.set("Charged Pauldrons of Ten Storms")
    .Armor.set(60)
    .InventoryType.SHOULDER.set()
    .ClassMask.SHAMAN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(34255)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Charged-TenStorms-Back')
    .Name.enGB.set("Charged Drape of Ten Storms")
    .Armor.set(60)
    .InventoryType.BACK.set()
    .ClassMask.SHAMAN.set(1)
    .Quality.HEIRLOOM.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(30783)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)

std.Items.create('default', 'Charged-TenStorms-Chest')
    .Name.enGB.set("Charged Chestguard of Ten Storms")
    .Armor.set(60)
    .InventoryType.CHEST.set()
    .ClassMask.SHAMAN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(34081)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Charged-TenStorms-Wrist')
    .Name.enGB.set("Charged Bracers of Ten Storms")
    .Armor.set(60)
    .InventoryType.WRISTS.set()
    .ClassMask.SHAMAN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(34079)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Charged-TenStorms-Hands')
    .Name.enGB.set("Charged Gauntlets of Ten Storms")
    .Armor.set(60)
    .InventoryType.HANDS.set()
    .ClassMask.SHAMAN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(34082)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Charged-TenStorms-Waist')
    .Name.enGB.set("Charged Belt of Ten Storms")
    .Armor.set(60)
    .InventoryType.WAIST.set()
    .ClassMask.SHAMAN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(34078)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Charged-TenStorms-Legs')
    .Name.enGB.set("Charged Legguards of Ten Storms")
    .Armor.set(60)
    .InventoryType.LEGS.set()
    .ClassMask.SHAMAN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(34084)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Charged-TenStorms-Feet')
    .Name.enGB.set("Charged Boots of Ten Storms")
    .Armor.set(60)
    .InventoryType.FEET.set()
    .ClassMask.SHAMAN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(34083)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

// One-handed Mace
std.Items.create('default', 'Charged-TenStorms-Mace')
    .Name.enGB.set("Charged Mace of Ten Storms")
    .Bonding.BINDS_ON_PICKUP.set()
    .Class.MACE_1H.set()
    .InventoryType.WEAPON.set()
    .Material.METAL.set()
    .SheatheType.set(1)
    .Quality.HEIRLOOM.set()
    .Flags.set(['REFUNDABLE', 'BIND_TO_ACCOUNT'])
    .Damage.add('PHYSICAL', 1, 0)
    .Delay.set(1800)
    .Price.BuyCount.set(1)
    .RequiredLevel.set(1)
    .ItemLevel.set(264)
    .MaxStack.set(1)
    .Sheath.set(1)
    .SoundOverride.set(-1)
    .DisplayInfo.set(35116)
    .ScalingStats.set(2, 1032)

// Shield
std.Items.create('default', 'Charged-TenStorms-Shield')
    .Name.enGB.set("Charged Shield of Ten Storms")
    .Bonding.BINDS_ON_PICKUP.set()
    .InventoryType.SHIELD.set()
    .Material.METAL.set()
    .Quality.HEIRLOOM.set()
    .Flags.set(['REFUNDABLE', 'BIND_TO_ACCOUNT'])
    .Armor.set(60)
    .Block.set(10)
    .Price.BuyCount.set(1)
    .RequiredLevel.set(1)
    .ItemLevel.set(264)
    .MaxStack.set(1)
    .SoundOverride.set(-1)
    .DisplayInfo.set(30872)
    .ScalingStats.set(376, 8388616)

std.Items.create('default', 'Master-Totem')
    .Name.enGB.set('Master Totem')
    .ItemSetName.enGB.set('Master Totem')
    .Bonding.BINDS_ON_PICKUP.set()
    .Description.enGB.set('This is a Master Totem, used by Shamans to channel their powers. It is a symbol of mastery over the elements. It channels the energies of Earth, Fire, Water and Air Elementals.')
    .Class.SIGIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Material.JEWELRY.set()
    .InventoryType.RELIC.set()
    .TotemCategory.MASTER_TOTEM.set()
    .Quality.HEIRLOOM.set()
    .Flags.set(['HEROIC', 'BIND_TO_ACCOUNT'])
    .Price.BuyCount.set(1)
    .ItemLevel.set(4)
    .MaxStack.set(1)
    .SoundOverride.set(-1)
    .DisplayInfo.modRefCopy('mod', 'master-totem', x => x
        .Icon.set('Spell_Totem_WardOfDraining')
        .GroupSoundIndex.set(12)
    )

std.ItemSet.create('default', 'Charged-TenStorms-Set')
    .Name.enGB.set('Charged Ten Storms Set')
    .Items.addId(60081) // Head
    .Items.addId(60082) // Shoulders
    .Items.addId(60083) // Back
    .Items.addId(60084) // Chest
    .Items.addId(60085) // Wrists
    .Items.addId(60086) // Hands
    .Items.addId(60087) // Waist
    .Items.addId(60088) // Legs
    .Items.addId(60089) // Feet
    .Spells.addMod(x => x
        .Spell.set(21899)
        .Threshold.set(3)
    )
    .Spells.addMod(x => x
        .Spell.set(23570)
        .Threshold.set(5)
    )
    .Spells.addMod(x => x
        .Spell.set(23551)
        .Threshold.set(8)
)

std.ItemSet.create('default', 'Charged-TenStorms-Weapon-Set')
    .Name.enGB.set('Charged Ten Storms Weapon Set')
    .Items.addId(60090) // Mace
    .Items.addId(60091) // Shield
    .Items.addId(60104) // Master Totem
    .Spells.addMod(x => x
        .Spell.set(14946)
        .Threshold.set(3)
    )