import { std } from "wow/wotlk";
import { ScalingStatDistributionDBCFile } from "wow/wotlk/dbc/ScalingStatDistribution";
import { ScalingStatValuesDBCFile } from "wow/wotlk/dbc/ScalingStatValues";

// Dragonstalker's Set (Singed) Heirlooms

std.Items.create('default', 'Singed-Dragonstalker-Helm')
    .Name.enGB.set("Singed Dragonstalker's Helm")
    .Armor.set(60)
    .InventoryType.HEAD.set()
    .ClassMask.HUNTER.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(34367)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(374, 65)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Singed-Dragonstalker-Shoulder')
    .Name.enGB.set("Singed Dragonstalker's Spaulders")
    .Armor.set(60)
    .InventoryType.SHOULDER.set()
    .ClassMask.HUNTER.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(34091)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(374, 65)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Singed-Dragonstalker-Chest')
    .Name.enGB.set("Singed Dragonstalker's Breastplate")
    .Armor.set(60)
    .InventoryType.CHEST.set()
    .ClassMask.HUNTER.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(33667)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(374, 65)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Singed-Dragonstalker-Wrist')
    .Name.enGB.set("Singed Dragonstalker's Bracers")
    .Armor.set(60)
    .InventoryType.WRISTS.set()
    .ClassMask.HUNTER.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(33666)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(374, 65)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Singed-Dragonstalker-Hands')
    .Name.enGB.set("Singed Dragonstalker's Gauntlets")
    .Armor.set(60)
    .InventoryType.HANDS.set()
    .ClassMask.HUNTER.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(33668)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(374, 65)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Singed-Dragonstalker-Waist')
    .Name.enGB.set("Singed Dragonstalker's Belt")
    .Armor.set(60)
    .InventoryType.WAIST.set()
    .ClassMask.HUNTER.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(33665)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(374, 65)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Singed-Dragonstalker-Legs')
    .Name.enGB.set("Singed Dragonstalker's Legguards")
    .Armor.set(60)
    .InventoryType.LEGS.set()
    .ClassMask.HUNTER.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(33672)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(374, 65)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Singed-Dragonstalker-Feet')
    .Name.enGB.set("Singed Dragonstalker's Boots")
    .Armor.set(60)
    .InventoryType.FEET.set()
    .ClassMask.HUNTER.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(34269)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(374, 65)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Singed-Dragonstalker-Back')
    .Name.enGB.set("Singed Dragonstalker's Drape")
    .Armor.set(60)
    .InventoryType.BACK.set()
    .ClassMask.HUNTER.set(1)
    .Quality.HEIRLOOM.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(30849)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(374, 65)
    .ItemLevel.set(264)


std.Items.create('default', 'Singed-Dragonstalker-Polearm')
    .Name.enGB.set("Singed Dragonstalker's Pike")
    .Bonding.BINDS_ON_PICKUP.set()
    .Class.POLEARM.set()
    .InventoryType.TWOHAND.set()
    .Material.METAL.set()
    .SheatheType.set(1)
    .Quality.set(7)
    .Flags.set(['REFUNDABLE', 'BIND_TO_ACCOUNT'])
    .Damage.add('PHYSICAL', 1, 0)
    .Delay.set(2900)
    .Price.BuyCount.set(1)
    .RequiredLevel.set(1)
    .ItemLevel.set(264)
    .MaxStack.set(1)
    .Sheath.set(1)
    .SoundOverride.set(-1)
    .DisplayInfo.set(28764)
    .Sheath.TWO_HANDED_WEAPON.set()
    .SheatheType.set(1)
    .ScalingStats.set(2, 1032)

std.ItemSet.create('default', 'Singed-Dragonstalker-Set')
    .Name.enGB.set('Singed Dragonstalker Set')
    .Items.addId(60070)
    .Items.addId(60071)
    .Items.addId(60072)
    .Items.addId(60073)
    .Items.addId(60074)
    .Items.addId(60075)
    .Items.addId(60076)
    .Items.addId(60077)
    .Spells.addMod(x => x
        .Spell.set(23559)
        .Threshold.set(3)
    )
    .Spells.addMod(x => x
        .Spell.set(21928)
        .Threshold.set(5)
    )
    .Spells.addMod(x => x
        .Spell.set(23578)
        .Threshold.set(8)
    )