import { std } from "wow/wotlk";

std.Items.create('default', 'Torn-Cover')
    .Name.enGB.set('Torn Nightslayer Cover')
    .Class.LEATHER_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(31514)
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .Quality.HEIRLOOM.set()
    .InventoryType.HEAD.set()
    .Class.LEATHER_EQUIP.set()
    .ScalingStats.set(374, 8388616)
    .ItemLevel.set(264)

std.Items.create('default', 'Torn-Shoulder-Pads')
    .Name.enGB.set('Torn Nightslayer Shoulder Pads')
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(31504)
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .Quality.HEIRLOOM.set()
    .InventoryType.SHOULDER.set()
    .Class.LEATHER_EQUIP.set()
    .ScalingStats.set(374, 8388616)
    .ItemLevel.set(264)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.Items.create('default', 'Torn-Chest')
    .Name.enGB.set('Torn Nightslayer Chestpiece')
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(31105)
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .Quality.HEIRLOOM.set()
    .InventoryType.CHEST.set()
    .Class.LEATHER_EQUIP.set()
    .ScalingStats.set(374, 8388616)
    .ItemLevel.set(264)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.Items.create('default', 'Torn-Wrist')
    .Name.enGB.set('Torn Nightslayer Bracelets')
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(31106)
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .Quality.HEIRLOOM.set()
    .InventoryType.WRISTS.set()
    .Class.LEATHER_EQUIP.set()
    .ScalingStats.set(374, 8388616)
    .ItemLevel.set(264)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.Items.create('default', 'Torn-hands')
    .Name.enGB.set('Torn Nightslayer Gloves')
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(31503)
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .Quality.HEIRLOOM.set()
    .InventoryType.HANDS.set()
    .Class.LEATHER_EQUIP.set()
    .ScalingStats.set(374, 8388616)
    .ItemLevel.set(264)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.Items.create('default', 'Torn-Waist')
    .Name.enGB.set('Torn Nightslayer Belt')
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(31339)
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .Quality.HEIRLOOM.set()
    .InventoryType.WAIST.set()
    .Class.LEATHER_EQUIP.set()
    .ScalingStats.set(374, 8388616)
    .ItemLevel.set(264)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.Items.create('default', 'Torn-Legs')
    .Name.enGB.set('Torn Nightslayer Pants')
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(31340)
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .Quality.HEIRLOOM.set()
    .InventoryType.LEGS.set()
    .Class.LEATHER_EQUIP.set()
    .ScalingStats.set(374, 8388616)
    .ItemLevel.set(264)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.Items.create('default', 'Torn-Feet')
    .Name.enGB.set('Torn Nightslayer Boots')
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(31109)
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .Quality.HEIRLOOM.set()
    .InventoryType.FEET.set()
    .Class.LEATHER_EQUIP.set()
    .ScalingStats.set(374, 8388616)
    .ItemLevel.set(264)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.Items.create('default', 'Torn-Back')
    .Name.enGB.set('Ancient Bloodmoon Cloak')
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(28891)
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .Quality.HEIRLOOM.set()
    .InventoryType.BACK.set()
    .ScalingStats.set(374, 8388616)
    .ItemLevel.set(264)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )

std.ItemSet.create('default', 'Torn-Heirloom-Set')
    .Name.enGB.set('Torn Nightslayer Set')
    .Items.addId(60023)
    .Items.addId(60024)
    .Items.addId(60025)
    .Items.addId(60026)
    .Items.addId(60027)
    .Items.addId(60028)
    .Items.addId(60029)
    .Items.addId(60030)
    .Spells.addMod(x=>x
        .Spell.set(21874)
        .Threshold.set(3)
    )
    .Spells.addMod(x=>x
        .Spell.set(21975)
        .Threshold.set(5)
    )
    .Spells.addMod(x=>x
        .Spell.set(23582)
        .Threshold.set(8)
    )