import { std } from "wow/wotlk";

// Overgrown Cenarion Heirlooms

std.Items.create('default', 'Overgrown-Cenarion-Helm')
    .Name.enGB.set("Overgrown Cenarion Helm")
    .Armor.set(60)
    .InventoryType.HEAD.set()
    .ClassMask.DRUID.set(1)
    .Quality.HEIRLOOM.set()
    .Class.LEATHER_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(32790)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(8)

std.Items.create('default', 'Overgrown-Cenarion-Shoulder')
    .Name.enGB.set("Overgrown Cenarion Spaulders")
    .Armor.set(60)
    .InventoryType.SHOULDER.set()
    .ClassMask.DRUID.set(1)
    .Quality.HEIRLOOM.set()
    .Class.LEATHER_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(32016)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(8)

std.Items.create('default', 'Overgrown-Cenarion-Back')
    .Name.enGB.set("Overgrown Cenarion Cloak")
    .Armor.set(60)
    .InventoryType.BACK.set()
    .ClassMask.DRUID.set(1)
    .Quality.HEIRLOOM.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(30850)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)

std.Items.create('default', 'Overgrown-Cenarion-Chest')
    .Name.enGB.set("Overgrown Cenarion Chestguard")
    .Armor.set(60)
    .InventoryType.CHEST.set()
    .ClassMask.DRUID.set(1)
    .Quality.HEIRLOOM.set()
    .Class.LEATHER_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(31797)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(8)

std.Items.create('default', 'Overgrown-Cenarion-Wrist')
    .Name.enGB.set("Overgrown Cenarion Bracers")
    .Armor.set(60)
    .InventoryType.WRISTS.set()
    .ClassMask.DRUID.set(1)
    .Quality.HEIRLOOM.set()
    .Class.LEATHER_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(31725)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(8)

std.Items.create('default', 'Overgrown-Cenarion-Hands')
    .Name.enGB.set("Overgrown Cenarion Gloves")
    .Armor.set(60)
    .InventoryType.HANDS.set()
    .ClassMask.DRUID.set(1)
    .Quality.HEIRLOOM.set()
    .Class.LEATHER_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(31726)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(8)

std.Items.create('default', 'Overgrown-Cenarion-Waist')
    .Name.enGB.set("Overgrown Cenarion Belt")
    .Armor.set(60)
    .InventoryType.WAIST.set()
    .ClassMask.DRUID.set(1)
    .Quality.HEIRLOOM.set()
    .Class.LEATHER_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(31722)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(8)

std.Items.create('default', 'Overgrown-Cenarion-Legs')
    .Name.enGB.set("Overgrown Cenarion Legguards")
    .Armor.set(60)
    .InventoryType.LEGS.set()
    .ClassMask.DRUID.set(1)
    .Quality.HEIRLOOM.set()
    .Class.LEATHER_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(31729)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(8)

std.Items.create('default', 'Overgrown-Cenarion-Feet')
    .Name.enGB.set("Overgrown Cenarion Boots")
    .Armor.set(60)
    .InventoryType.FEET.set()
    .ClassMask.DRUID.set(1)
    .Quality.HEIRLOOM.set()
    .Class.LEATHER_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(31724)
    .Spells.addMod(x => x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(376, 8388616)
    .ItemLevel.set(264)
    .Material.set(8)

// Staff (no spell)
std.Items.create('default', 'Overgrown-Cenarion-Staff')
    .Name.enGB.set("Overgrown Cenarion Staff")
    .Bonding.BINDS_ON_PICKUP.set()
    .Class.STAFF.set()
    .InventoryType.TWOHAND.set()
    .Material.WOOD.set()
    .SheatheType.set(2)
    .Quality.HEIRLOOM.set()
    .Flags.set(['REFUNDABLE', 'BIND_TO_ACCOUNT'])
    .Damage.add('PHYSICAL', 1, 0)
    .Delay.set(2500)
    .Price.BuyCount.set(1)
    .RequiredLevel.set(1)
    .ItemLevel.set(264)
    .MaxStack.set(1)
    .Sheath.set(2)
    .SoundOverride.set(-1)
    .DisplayInfo.set(33015)
    .ScalingStats.set(2, 1032)

// Set
std.ItemSet.create('default', 'Overgrown-Cenarion-Set')
    .Name.enGB.set('Overgrown Cenarion Set')
    .Items.addId(60092) // Head
    .Items.addId(60093) // Shoulders
    .Items.addId(60094) // Back
    .Items.addId(60095) // Chest
    .Items.addId(60096) // Wrists
    .Items.addId(60097) // Hands
    .Items.addId(60098) // Waist
    .Items.addId(60099) // Legs
    .Items.addId(60100) // Feet
    .Spells.addMod(x => x
        .Spell.set(23557)
        .Threshold.set(3)
    )
    .Spells.addMod(x => x
        .Spell.set(18382)
        .Threshold.set(5)
    )
    .Spells.addMod(x => x
        .Spell.set(23556)
        .Threshold.set(8)
    )