import { std } from "wow/wotlk";
import { ScalingStatDistributionDBCFile } from "wow/wotlk/dbc/ScalingStatDistribution";
import { ScalingStatValuesDBCFile } from "wow/wotlk/dbc/ScalingStatValues";

std.DBC.ScalingStatDistribution.add(373)
    .Maxlevel.set(80)
    .StatID.setIndex(0, 7)
    .StatID.setIndex(1, 32)
    .StatID.setIndex(2, 5)
    .StatID.setIndex(3, 45)
    .StatID.setIndex(4, 31)
    .StatID.setIndex(5, 38)

std.Items.create('default', 'Blemished-Penance-Helm')
    .Name.enGB.set('Blemished Mask of Penance')
    .Armor.set(60)
    .InventoryType.HEAD.set()
    .ClassMask.PALADIN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(42860)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(373, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Blemished-Penance-Shoulder')
    .Name.enGB.set('Blemished Pauldrons of Penance')
    .Armor.set(60)
    .InventoryType.SHOULDER.set()
    .ClassMask.PALADIN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(42853)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(373, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Blemished-Penance-Chest')
    .Name.enGB.set('Blemished Chestplate of Penance')
    .Armor.set(60)
    .InventoryType.CHEST.set()
    .ClassMask.PALADIN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(42863)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(373, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Blemished-Penance-Wrist')
    .Name.enGB.set('Blemished Vambraces of Penance')
    .Armor.set(60)
    .InventoryType.WRISTS.set()
    .ClassMask.PALADIN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(42851)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(373, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Blemished-Penance-Hands')
    .Name.enGB.set('Blemished Gauntlets of Penance')
    .Armor.set(60)
    .InventoryType.HANDS.set()
    .ClassMask.PALADIN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(43639)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(373, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Blemished-Penance-Waist')
    .Name.enGB.set('Blemished Girdle of Penance')
    .Armor.set(60)
    .InventoryType.WAIST.set()
    .ClassMask.PALADIN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(42862)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(373, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Blemished-Penance-Legs')
    .Name.enGB.set('Blemished Cassock of Penance')
    .Armor.set(60)
    .InventoryType.LEGS.set()
    .ClassMask.PALADIN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(42859)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(373, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Blemished-Penance-feet')
    .Name.enGB.set('Blemished Boots of Penance')
    .Armor.set(60)
    .InventoryType.FEET.set()
    .ClassMask.PALADIN.set(1)
    .Quality.HEIRLOOM.set()
    .Class.MAIL_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(42864)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(373, 8388616)
    .ItemLevel.set(264)
    .Material.set(6)

std.Items.create('default', 'Blemished-2H-Mace')
    .Name.enGB.set('Blemished Hammer of Divine Might')
    .Bonding.BINDS_ON_PICKUP.set()
    .Class.MACE_2H.set()
    .InventoryType.TWOHAND.set()
    .Material.METAL.set()
    .SheatheType.set(1)
    .Quality.set(7)
    .Flags.set(['REFUNDABLE','BIND_TO_ACCOUNT'])
    .Damage.add('PHYSICAL',1,0)
    .Delay.set(2900)
    .Price.BuyCount.set(1)
    .RequiredLevel.set(1)
    .ItemLevel.set(264)
    .MaxStack.set(1)
    .Sheath.set(1)
    .SoundOverride.set(-1)
    .DisplayInfo.set(2440)
    .Sheath.TWO_HANDED_WEAPON.set()
    .SheatheType.set(1)
    .ScalingStats.set(352, 1032)

std.Items.create('default', 'Blemished-Bishop-Back')
    .Name.enGB.set("Blemished Bishop's Cloak")
    .Armor.set(60)
    .InventoryType.BACK.set()
    .ClassMask.PALADIN.set(1)
    .Quality.HEIRLOOM.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Flags.set(["HEROIC", "BIND_TO_ACCOUNT"])
    .DisplayInfo.set(42611)
    .Spells.addMod(x=>x
        .Spell.set(57353)
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        .Trigger.ON_EQUIP.set()
    )
    .ScalingStats.set(373, 8388616)
    .ItemLevel.set(264)


std.ItemSet.create('default', 'Blemished-Penance-Set')
    .Name.enGB.set('Blemished Penance Set')
    .Items.addId(60012)
    .Items.addId(60013)
    .Items.addId(60014)
    .Items.addId(60015)
    .Items.addId(60016)
    .Items.addId(60017)
    .Items.addId(60018)
    .Items.addId(60019)
    .Spells.addMod(x=>x
        .Spell.set(23565)
        .Threshold.set(3)
    )
    .Spells.addMod(x=>x
        .Spell.set(24196)
        .Threshold.set(5)
    )
    .Spells.addMod(x=>x
        .Spell.set(23591)
        .Threshold.set(8)
    )
