import { std } from "wow/wotlk";

std.Items.create('mod', 'Oathseeker')
    .Name.enGB.set("Oathbreaker")
    .Description.enGB.set("Killing for the sake of killing... conquering for the sake of conquest... there is no honor in such things. There is only shame and regret. But yet you still do it, breaking your light-sworn Oath... You are, the Oathbreaker.")
    .ItemLevel.set(387)
    .InventoryType.WEAPON.set()
    .Class.SWORD_1H.set()
    .ClassMask.set("PALADIN")
    .Bonding.BINDS_ON_PICKUP.set()
    .Damage.addPhysical(699, 893)
    .Damage.addShadow(483, 677)
    .Delay.setAsMilliseconds(1900)
    .DisplayInfo.set(70015)
    .RequiredLevel.set(80)
    .Sheath.ONE_HANDED.set()
    .Price.set(1, 1, 1)
    .SheatheType.set(3)
    .Quality.set(7)
    .Flags.set(["HEROIC", "NO_DISENCHANT", "NO_EQUIP_COOLDOWN", "CANT_DESTROY"])

std.Items.create('mod', 'Oathseeker-Shield')
    .Name.enGB.set('False Defender')
    .Description.enGB.set("The Truth you once guarded is no more. The Oath you broke, is no more. The light that pierced the clouds to radiate your righteousness, not a Flame of falsehoods... Within your hand, the shield to defend what is left, The False Guard")
    .ItemLevel.set(386)
    .InventoryType.SHIELD.set()
    .Class.SHIELD_EQUIP.set()
    .ClassMask.set("PALADIN")
    .Bonding.BINDS_ON_PICKUP.set()
    .DisplayInfo.set(70019)
    .RequiredLevel.set(80)
    .Sheath.SHIELD.set()
    .Price.set(1, 1, 1)
    .SheatheType.set(4)
    .Quality.set(7)
    .Flags.set(["HEROIC", "NO_DISENCHANT", "NO_EQUIP_COOLDOWN", "CANT_DESTROY"])