import { std } from "wow/wotlk";

std.Items.create('mod', 'flamebringer')
    .Name.set({"enGB":"Flamebriger"})
    .Quality.set(7)
    .Flags.HEROIC.set(1)
    .ItemLevel.set(393)
    .InventoryType.TWOHAND.set()
    .Class.SWORD_2H.set()
    .DisplayInfo.set(70023)
    .Bonding.BINDS_ON_PICKUP.set()
    .Description.enGB.set("Ashes to ashes, flames may cleanse thy wretched bones, and may your next life, be better, than this.")
    .Damage.addHoly(1399, 1786)
    .Damage.addFire(483, 677)
    .Delay.setAsMilliseconds(3100)
    .RequiredLevel.set(1)
    .Sheath.TWO_HANDED_WEAPON.set()
    .Price.set(1, 1, 1)
    .SheatheType.set(1)
    .Quality.set(7)
    .Flags.set(["HEROIC", "NO_DISENCHANT", "NO_EQUIP_COOLDOWN", "CANT_DESTROY"])
    .Stats.add("STAMINA", 287)
    .Stats.add("ATTACK_POWER", 312)
    .Stats.add("SPELL_POWER", 323)
    .Stats.add("STRENGTH", 273)
    .Stats.add("HIT_RATING", 307)
    .Stats.add("INTELLECT", 267)
    .Stats.add("CRIT_RATING", 291)
    .Stats.add("ARMOR_PENETRATION_RATING", 259)
    .Spells.addMod((spell) => {
        spell.Spell.set(43224)
        .Charges.set("UNLIMITED")
        .Trigger.CHANCE_ON_HIT.set()
        .ProcsPerMinute.set(15)
    })