import { std } from "wow/wotlk";

// console.log(std.Spells.load(32289).codify({}))

std.Items.create('mod', 'loveyoudu-staff')
    .Name.enGB.set("Dragonwrath, Tarecgosa's Rest")
    .Description.set({"enGB":"For aiding the Titans to creating Time-Warped Weapons, they bestowed Dragonwrath to Loveyoudu."})
    .InventoryType.TWOHAND.set()
    .Quality.ORANGE.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .RequiredLevel.set(80)
    .Flags.set(["BIND_TO_ACCOUNT", "CANT_DESTROY", "HEROIC", "ARENA_DISABLED"])
    .Socket.addRed()
    .Socket.addRed()
    .Socket.addRed()
    .SocketBonus.set(3353)
    .Class.STAFF.set()
    .SheatheType.set(2)
    .Sheath.STAFF.set()
    .DisplayInfo.set(70022)
    .Delay.setAsMilliseconds(3300)
    .Damage.add("PHYSICAL", 2344, 3517)
    .Stats.addStamina(730)
    .Stats.addIntellect(426)
    .Stats.addSpirit(423)
    .Stats.addHitRating(310)
    .Stats.addHasteRating(620)
    .Stats.addSpellPower(2786)