import { std } from "wow/wotlk";

std.Items.create('mod', 'fate')
    .Name.enGB.set("The Dreadblades")
    .Description.enGB.set("She saw herself commanding an impossibly large pirate fleet, one that could conquer the high seas and all the nations of Azeroth. Every ship that dared to challenge her burned, and every city gave up its treasures or was destroyed.")
    .ItemLevel.set(392)
    .InventoryType.MAINHAND.set()
    .Class.SWORD_1H.set()
    .ClassMask.set("ROGUE")
    .Bonding.BINDS_ON_PICKUP.set()
    .Damage.addPhysical(699, 893)
    .Damage.addShadow(483, 677)
    .Delay.setAsMilliseconds(1900)
    .DisplayInfo.set(70016)
    .RequiredLevel.set(80)
    .Sheath.ONE_HANDED.set()
    .Price.set(1, 1, 1)
    .SheatheType.set(3)
    .Quality.set(7)
    .Flags.set(["HEROIC", "NO_DISENCHANT", "NO_EQUIP_COOLDOWN", "CANT_DESTROY"])

std.Items.create('mod', 'fortune')
    .Name.enGB.set("The Dreadblades")
    .Description.enGB.set("No blade can shed the blood of so many innocents and not demand a toll on its wielder as well. They are no treasure.")
    .ItemLevel.set(391)
    .InventoryType.OFFHAND.set()
    .Class.SWORD_1H.set()
    .ClassMask.set("ROGUE")
    .Bonding.BINDS_ON_PICKUP.set()
    .Damage.addPhysical(699, 893)
    .Damage.addShadow(483, 677)
    .Delay.setAsMilliseconds(1900)
    .DisplayInfo.set(70016)
    .RequiredLevel.set(80)
    .Sheath.ONE_HANDED.set()
    .Price.set(1, 1, 1)
    .SheatheType.set(3)
    .Quality.set(7)
    .Flags.set(["HEROIC", "NO_DISENCHANT", "NO_EQUIP_COOLDOWN", "CANT_DESTROY"])