import { std } from "wow/wotlk";

std.Items.create('mod', 'ashbringer-shattered')
    .Name.enGB.set("Shattered Ashbringer")
    .ItemLevel.set(390)
    .InventoryType.TWOHAND.set()
    .Class.SWORD_2H.set()
    .Bonding.BINDS_ON_EQUIP.set()
    .Description.enGB.set("Alexandros Spirit at rest, this is all that Remains of the Legacy of the Ashbringer.")
    .Damage.addPhysical(1399, 1786)
    .Damage.addHoly(483, 677)
    .Delay.setAsMilliseconds(3100)
    .DisplayInfo.set(70010)
    .Sheath.TWO_HANDED_WEAPON.set()
    .Price.set(1, 1, 1)
    .SheatheType.set(1)
    .Quality.set(7)
    .Flags.set(["HEROIC", "NO_DISENCHANT", "NO_EQUIP_COOLDOWN", "CANT_DESTROY"])
    .Stats.add("STAMINA", 287)
    .Stats.add("ATTACK_POWER", 312)
    .Stats.add("SPELL_POWER", 323)
    .Stats.add("STRENGTH", 273)
    .Stats.add("HIT_RATING", 307)
    .Stats.add("INTELLECT", 267)
    .Stats.add("CRIT_RATING", 291)
    .Stats.add("ARMOR_PENETRATION_RATING", 259)
    .Spells.addMod((spell) => {
        spell.Spell.set(43224)
        .Charges.set("UNLIMITED")
        .Trigger.CHANCE_ON_HIT.set()
        .ProcsPerMinute.set(15)
    })