import { std } from "wow/wotlk";

std.Items.create('mod', 'warrior-legacy-1')
    .Name.enGB.set("Warswords of the Valarjar")
    .ItemLevel.set(389)
    .InventoryType.MAINHAND.set()
    .Class.SWORD_2H.set()
    .ClassMask.set("WARRIOR")
    .Socket.addRed()
    .SocketBonus.set(3877)
    .Bonding.BINDS_ON_PICKUP.set()
    .Description.enGB.set("Helya's betrayal shall never be forgiven. Let her rot beneath the waves, far from the Halls of Valor.")
    .Damage.addPhysical(893, 1344)
    .Damage.addNature(241, 339)
    .Delay.setAsMilliseconds(2900)
    .DisplayInfo.set(70005)
    .RequiredLevel.set(80)
    .Sheath.TWO_HANDED_WEAPON.set()
    .Price.set(1, 1, 1)
    .SheatheType.set(1)
    .Quality.set(7)
    .Flags.set(["HEROIC", "NO_DISENCHANT", "NO_EQUIP_COOLDOWN", "CANT_DESTROY"])
    .Stats.add("STAMINA", 287)
    .Stats.add("ATTACK_POWER", 312)
    .Stats.add("AGILITY", 281)
    .Stats.add("EXPERTISE_RATING", 323)
    .Stats.add("STRENGTH", 273)
    .Stats.add("HIT_RATING", 307)
    .Stats.add("CRIT_RATING", 291)
    .Stats.add("ARMOR_PENETRATION_RATING", 259)
    .Spells.addMod(x => x 
        .Spell.set(80912)
        .Trigger.ON_EQUIP.set()
        .Charges.set("UNLIMITED")
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        )

std.Items.create('mod', 'warrior-legacy-2')
    .Name.enGB.set("Warswords of the Valarjar")
    .ItemLevel.set(388)
    .InventoryType.OFFHAND.set()
    .Class.SWORD_2H.set()
    .ClassMask.set("WARRIOR")
    .Bonding.BINDS_ON_PICKUP.set()
    .Description.enGB.set("In truth, it is her power that makes these weapons truly magnificent. Her power, laced with her hatred, crashes endlessly against Odyn's spirit. The tension between those energies will forever permeate these blades...")
    .Damage.addPhysical(893, 1344)
    .Damage.addNature(241, 339)
    .Delay.setAsMilliseconds(2900)
    .DisplayInfo.set(70005)
    .RequiredLevel.set(80)
    .Sheath.TWO_HANDED_WEAPON.set()
    .SheatheType.set(1)
    .Quality.set(7)
    .Flags.set(["HEROIC", "NO_DISENCHANT", "NO_EQUIP_COOLDOWN", "CANT_DESTROY"])
    .Stats.add("STAMINA", 287)
    .Stats.add("ATTACK_POWER", 312)
    .Stats.add("AGILITY", 281)
    .Stats.add("EXPERTISE_RATING", 323)
    .Stats.add("STRENGTH", 273)
    .Stats.add("HIT_RATING", 307)
    .Stats.add("CRIT_RATING", 291)
    .Stats.add("ARMOR_PENETRATION_RATING", 259)
    .Spells.addMod(x => x 
        .Spell.set(80911)
        .Trigger.ON_EQUIP.set()
        .Charges.set("UNLIMITED")
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        )