import { std } from "wow/wotlk";

// console.log(std.Items.load(34334).codify({}))

std.Items.create('mod', 'windrunner')
    .Name.set({"enGB":"Thas'dorah, Legacy of the Windrunners","deDE":"Thas'dorah, Erbstück von Haus Windläufer"})
    .ItemLevel.set(394)
    .InventoryType.RANGED.set()
    .AmmoType.NONE.set()
    .Class.BOW.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .Description.enGB.set("When it was retrieved from the Sunwell, the bow radiated power. Talanas was humbled by the gift. He named the weapon Thas'dorah, Valor of the Forest.")
    .Damage.addPhysical(1399, 1786)
    .Damage.addNature(483, 677)
    .Delay.setAsMilliseconds(2300)
    .RangeMod.set(128)
    .RequiredLevel.set(80)
    .Sheath.TWO_HANDED_WEAPON.set()
    .Price.set(1, 1, 1)
    .SheatheType.set(2)
    .Quality.set(7)
    .Flags.set(["HEROIC", "NO_DISENCHANT", "NO_EQUIP_COOLDOWN", "CANT_DESTROY"])
    .Stats.add("STAMINA", 287)
    .Stats.add("ATTACK_POWER", 312)
    .Stats.add("AGILITY", 273)
    .Stats.add("HIT_RATING", 307)
    .Stats.add("CRIT_RATING", 291)
    .Stats.add("ARMOR_PENETRATION_RATING", 259)
    .Spells.addMod(x=>x 
        .Spell.set(15806)
        .Trigger.ON_EQUIP.set()
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        )
    .Spells.addMod(x=>x 
        .Spell.set(46699)
        .Trigger.ON_EQUIP.set()
        .CategoryCooldown.set(-1)
        .Cooldown.set(-1)
        )
    .DisplayInfo.modRefCopy('mod','windrunner-legacy-item',x=>x
        .Icon.set('inv_bow_1h_artifactwindrunner_d_03')
        .SpellVisual.modRefCopy(x=>x
            .CastKit.modRefCopy(x=>x
                .CameraShake.set(0)
                .Flags.set(0)
                .Sound.set(1146)
                .Animation.ATTACK_BOW.set()
                .StartAnimation.set(-1)
            )
            .ImpactKit.modRefCopy(x=>x
                .CameraShake.set(0)
                .Flags.set(0)
                .Sound.set(4296)
                .Animation.COMBAT_WOUND.set()
                .StartAnimation.set(-1)
            )
            .PrecastKit.modRefCopy(x=>x
                .CameraShake.set(0)
                .Flags.set(0)
                .Sound.set(1144)
                .Animation.LOAD_BOW.set()
                .StartAnimation.set(-1)
            )
        )
        .Models.set(0,'bow_1h_artifactwindrunner_d_03.mdx', 'bow_1h_artifactwindrunner_d_03_purple')
        .GroupSoundIndex.set(12)
    )