import { std } from "wow/wotlk";
import { ItemTemplate } from "wow/wotlk/std/Item/ItemTemplate";
import { LICH_CLASS ,LICH_CONSTANTS } from "./lich-class";

const SHARED_VALUES = {
    MACE_NAME: "Acolyte's Dagger",
    OFFHAND_NAME: "Book of Damnation",
    WAND_NAME: "Acolyte's Wand",
    COWL_NAME: "Cowl of Lesser Necromancy",
    CLOAK_NAME: "Cloak of Necessary Evils",
    ROBE_NAME: "Necromantic Acolyte Robe",
    GLOVE_NAME: "Acolyte's Gloves",
    BELT_NAME: "Belt of the Acolyte",
    SHOULDER_NAME: "Acolyte's Shoulderpads",
    LEGGINGS_NAME: "Acolyte's Leggings",
    BOOTS_NAME: "Acolyte's Shoes",
    SHIRT_NAME: "Only Good Shirt",
}

const DAGGER = std.Items.create(LICH_CONSTANTS.MODULE_NAME, SHARED_VALUES.MACE_NAME)
    .Name.enGB.set(SHARED_VALUES.MACE_NAME)
    .InventoryType.MAINHAND.set()
    .SheatheType.set(3)
    .Sheath.ONE_HANDED.set()    
    .Class.DAGGER.set()
    .DisplayInfo.set(36650)
    .Quality.GREEN.set()
    .Damage.addPhysical(17, 32)
    .Damage.addShadow(12, 27)
    .Stats.add("STAMINA", 3)
    .Stats.add("INTELLECT", 6)
    .Stats.add("SPELL_POWER", 20)
    .Delay.addMilliseconds(1500)
    .Durability.set(16)
    .ItemLevel.set(21)
    .ClassMask.set(LICH_CLASS.Mask)
    .Bonding.BINDS_ON_PICKUP.set()
    .Price.PlayerSellPrice.addCopper(6)

const OFFHAND = std.Items.create(LICH_CONSTANTS.MODULE_NAME, SHARED_VALUES.OFFHAND_NAME)
    .Name.enGB.set(SHARED_VALUES.OFFHAND_NAME)
    .InventoryType.OFFHAND.set()
    .SheatheType.set(7)
    .Sheath.OFFHAND.set()
    .DisplayInfo.set(51682)
    .ClassMask.set(LICH_CLASS.Mask)
    .Quality.GREEN.set()
    .ItemLevel.set(25)
    .Bonding.BINDS_ON_PICKUP.set()
    .Class.MISC.set()
    .Armor.set(71)
    .Stats.add("STAMINA", 11)
    .Stats.add("INTELLECT", 7)
    .Stats.add("SPELL_POWER", 22)
    .Stats.add("CRIT_RATING", 31)
    .Spells.addMod((spell) => {
        spell.Spell.set(42650)
        .Charges.Raw.set(0)
        .Cooldown.set(150000)
        .Trigger.ON_USE.set()
    })

const WAND = std.Items.create(LICH_CONSTANTS.MODULE_NAME, SHARED_VALUES.WAND_NAME)
    .Name.enGB.set(SHARED_VALUES.WAND_NAME)
    .InventoryType.RANGED.set()
    .Class.WAND.set()
    .ClassMask.set(LICH_CLASS.Mask)
    .Bonding.BINDS_ON_PICKUP.set()
    .Damage.addShadow(24, 45)
    .DisplayInfo.set(28159)
    .Delay.addMilliseconds(1400)
    .ItemLevel.set(25)
    .Quality.GREEN.set()
    .Price.PlayerSellPrice.addCopper(7)
    .Sheath.NONE.set()
    .RangeMod.set(100)
    .Stats.addSpellPenetration(13)

const COWL = std.Items.create(LICH_CONSTANTS.MODULE_NAME, SHARED_VALUES.COWL_NAME)
    .Name.enGB.set(SHARED_VALUES.COWL_NAME)
    .Quality.GREEN.set()
    .DisplayInfo.set(15295)
    .InventoryType.HEAD.set()
    .Class.CLOTH_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .ClassMask.set(LICH_CLASS.Mask)
    .ItemLevel.set(25)
    .Stats.addStamina(5)
    .Stats.addIntellect(9)
    .Stats.addSpellPower(13)


const SHOULDER = std.Items.create(LICH_CONSTANTS.MODULE_NAME, SHARED_VALUES.SHOULDER_NAME)
    .Name.enGB.set(SHARED_VALUES.SHOULDER_NAME)
    .Quality.GREEN.set()
    .DisplayInfo.set(28729)
    .InventoryType.SHOULDER.set()
    .Class.CLOTH_EQUIP.set()
    .ClassMask.set(LICH_CLASS.Mask)
    .Bonding.BINDS_ON_PICKUP.set()
    .Armor.set(63)
    .Durability.set(25)
    .ItemLevel.set(25)
    .Stats.addIntellect(9)
    .Stats.addSpellPower(5)

const CLOAK = std.Items.create(LICH_CONSTANTS.MODULE_NAME, SHARED_VALUES.CLOAK_NAME)
    .Name.enGB.set(SHARED_VALUES.CLOAK_NAME)
    .DisplayInfo.set(28891)
    .InventoryType.BACK.set()
    .ClassMask.set(LICH_CLASS.Mask)
    .Quality.GREEN.set()
    .Armor.set(23)
    .Stats.addIntellect(5)
    .Stats.addStamina(8)
    .Stats.addHitRating(12)
    .Bonding.BINDS_ON_PICKUP.set()

const ROBE = std.Items.create(LICH_CONSTANTS.MODULE_NAME, SHARED_VALUES.ROBE_NAME)
    .Name.enGB.set(SHARED_VALUES.ROBE_NAME)
    .Armor.set(84)
    .DisplayInfo.set(12696)
    .Class.CLOTH_EQUIP.set()
    .InventoryType.CHEST.set()
    .Quality.GREEN.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .ClassMask.set(LICH_CLASS.Mask)
    .Durability.set(35)
    .Description.enGB.set("Not quite Kirin'tor but this fits just as well.")
    .Stats.addStamina(6)
    .Stats.addIntellect(10)

const GLOVES = std.Items.create(LICH_CONSTANTS.MODULE_NAME, SHARED_VALUES.GLOVE_NAME)
    .Name.enGB.set(SHARED_VALUES.GLOVE_NAME)
    .Quality.GREEN.set()
    .DisplayInfo.set(15008)
    .InventoryType.HANDS.set()
    .Class.CLOTH_EQUIP.set()
    .Bonding.BINDS_ON_PICKUP.set()
    .ClassMask.set(LICH_CLASS.Mask)
    .Durability.set(30)
    .Stats.addIntellect(6)
    .Stats.addSpellPower(9)

const BELT = std.Items.create(LICH_CONSTANTS.MODULE_NAME, SHARED_VALUES.BELT_NAME)
    .Name.enGB.set(SHARED_VALUES.BELT_NAME)
    .DisplayInfo.set(11533)
    .InventoryType.WAIST.set()
    .Class.CLOTH_EQUIP.set()
    .ClassMask.set(LICH_CLASS.Mask)
    .Bonding.BINDS_ON_PICKUP.set()
    .Durability.set(20)
    .Quality.GREEN.set()
    .Stats.addStamina(4)
    .Stats.addSpirit(12)

const BOOTS = std.Items.create(LICH_CONSTANTS.MODULE_NAME, SHARED_VALUES.BOOTS_NAME)
    .Name.enGB.set(SHARED_VALUES.BOOTS_NAME)
    .Quality.GREEN.set()
    .DisplayInfo.set(22034)
    .InventoryType.FEET.set()
    .Class.CLOTH_EQUIP.set()
    .Armor.set(2)
    .Bonding.BINDS_ON_PICKUP.set()
    .ClassMask.set(LICH_CLASS.Mask)
    .Armor.set(49)
    .Stats.addStamina(7)
    .Stats.addIntellect(5)

const LEGGINGS = std.Items.create(LICH_CONSTANTS.MODULE_NAME, SHARED_VALUES.LEGGINGS_NAME, 1395)
    .Name.enGB.set(SHARED_VALUES.LEGGINGS_NAME)
    .Quality.GREEN.set()
    .Class.CLOTH_EQUIP.set()
    .InventoryType.LEGS.set(    )
    .Bonding.BINDS_ON_PICKUP.set()
    .ClassMask.set(LICH_CLASS.Mask)
    .Stats.add("STAMINA", 7)
    .Stats.add("INTELLECT", 8)
    .Armor.set(54)

const GEAR = [ COWL, SHOULDER, ROBE, CLOAK, BOOTS, LEGGINGS, DAGGER, OFFHAND, WAND]

std.Items.create('mod', 'apprentice-soulkeeper')
    .Name.enGB.set("Acolyte's Soulkeeper")
    .Quality.GREEN.set()
    .DisplayInfo.set(20272)
    .InventoryType.TWOHAND.set()
    .Class.STAFF.set()
    .SheatheType.set(2)
    .Sheath.STAFF.set()
    .ClassMask.set(LICH_CLASS.Mask)
    .Damage.addPhysical(41, 66)
    .Damage.addShadow(23, 41)
    .Delay.setAsMilliseconds(2700)
    .Stats.addStamina(8)
    .Stats.addIntellect(13)
    .Stats.addHasteRating(12)
    .Stats.addHitRating(9)

for (let classRacePair of LICH_CLASS.Races.get()) {
    classRacePair.Outfits.both((srg) => {
        srg.Items.clearAll()
        srg.Items.add(6948)
        srg.Items.add(60135)
        for (let item of GEAR) {
            srg.Items.add(item.ID)
        }
    })
}